permalink: /:year/:month/:title 

exclude: ['.git', '.gitignore', 'README.md', 'Rakefile']

paginate: 15

auto: true

markdown: kramdown

kramdown:
  use_coderay: true

title: More Than Nothing
description: The blog of Andrew January
author:
  name: Andrew January
  email: andrewjanuary@gmail.com
  github: ajanuary
  twitter: ajanuary

url: http://mtn-blog.herokuapp.com
mediaurl: http://mtn-blog.s3.amazonaws.com